[package]
name = "fretboard"
version = "0.1.0"
edition = "2024"

[dependencies]
catppuccin = "2.6.0"
env_logger = "0.11.8"
iced = { version = "0.14.0", features = ["advanced", "tokio"] }
log = "0.4.29"
serde = "1.0.228"
toml = "0.9.11"
xdg = "3.0.0"
