[package]
name = "fretboard"
version = "0.1.0"
edition = "2024"

[dependencies]
catppuccin = "2.6.0"
env_logger = "0.11.8"
iced = { version = "0.14.0", features = ["advanced", "tokio"] }
knus = "3.3.1"
log = "0.4.29"
miette = { version = "7.6.0", features = ["fancy"] }
xdg = "3.0.0"
